# Generated by Django 4.2.3 on 2023-08-05 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('profile_pic', models.ImageField(default='usericon.jpg', upload_to='profile_pic/')),
                ('user_type', models.CharField(default='student', max_length=50)),
                ('dob', models.DateField(auto_now_add=True)),
                ('gender', models.CharField(default='Others', max_length=50)),
                ('religion', models.CharField(default='', max_length=50)),
                ('mobile', models.PositiveIntegerField(default='')),
                ('father_name', models.CharField(default='', max_length=50)),
                ('mother_name', models.CharField(default='', max_length=50)),
                ('father_occu', models.CharField(default='', max_length=50)),
                ('femail', models.EmailField(default='', max_length=254)),
                ('fmobile', models.PositiveIntegerField()),
                ('present_addr', models.CharField(default='', max_length=50)),
                ('permanent_addr', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
