# Generated by Django 4.2.3 on 2023-08-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='femail',
            field=models.EmailField(max_length=254),
        ),
    ]
