# Generated by Django 4.2.3 on 2023-08-05 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_user_femail'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mother_occu',
            field=models.CharField(default='', max_length=50),
        ),
    ]
