# Generated by Django 4.2.3 on 2023-08-07 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_user_mother_occu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='religion',
        ),
    ]
