# Generated by Django 4.2.3 on 2023-08-08 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_alter_user_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='branch',
            field=models.CharField(default='', max_length=50),
        ),
    ]
