# Generated by Django 4.2.3 on 2023-08-08 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_user_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fmobile',
            field=models.PositiveIntegerField(default=''),
        ),
    ]
