# Generated by Django 4.2.4 on 2023-10-21 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_holday_alter_user_branch'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Holday',
            new_name='Holiday',
        ),
    ]
